name: generate animation

on:
  # 每天午夜自动运行
  schedule:
    - cron: "0 0,12 * * *"
    - cron: "0 6,18 * * *"
  
  # 允许手动触发
  workflow_dispatch:
  
  # 在主分支推送时运行
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # 生成贪吃蛇游戏作为 SVG 动画
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: XCQ0607
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 将生成的文件推送到 output 分支
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
